import "server-only";

import { connection } from "next/server";
import type { Pool, QueryResultRow } from "pg";

import { getReadOnlyPool } from "./pool";
import { PAGE_SIZE, isUuid, parseFeedQuery } from "./query-params";
import {
  buildChannelSummaryQuery,
  buildFeedQueries,
  buildSidebarChannelsQuery,
  buildTagFeedQueries,
  buildTagSummaryQuery,
  buildTagsQuery,
  buildTopTagsQuery,
  type PagedSqlQueries,
  type SqlQuery,
} from "./queries";
import type {
  ChannelDetail,
  ChannelFeedQueryInput,
  ChannelSummary,
  FeedPost,
  FeedQueryInput,
  FeedTag,
  PaginatedResult,
  SidebarData,
  TagDetail,
  TagSummary,
} from "./types";

export { PAGE_SIZE, parseFeedQuery, parsePage, parseQuery } from "./query-params";
export type {
  ChannelDetail,
  ChannelFeedQueryInput,
  ChannelSummary,
  FeedChannel,
  FeedMode,
  FeedPost,
  FeedQueryInput,
  FeedTag,
  PaginatedResult,
  SidebarData,
  TagDetail,
  TagSummary,
} from "./types";

const SIDEBAR_CHANNEL_LIMIT = 12;
const SIDEBAR_TAG_LIMIT = 10;

interface CountRow extends QueryResultRow {
  total_count: string | number;
}

interface FeedRow extends QueryResultRow {
  video_id: string;
  subtitle_id: string;
  youtube_video_id: string;
  video_title: string;
  video_url: string;
  video_description: string | null;
  duration_seconds: number | null;
  published_at: Date | string | null;
  transcript: string;
  language_code: string;
  language_name: string | null;
  is_auto_generated: boolean;
  channel_id: string;
  channel_title: string;
  channel_handle: string | null;
  channel_url: string;
  channel_description: string | null;
  channel_avatar_url: string | null;
  tags: unknown;
}

interface TagSummaryRow extends QueryResultRow {
  id: string;
  name: string;
  category: string | null;
  description: string | null;
  post_count: string | number;
}

interface ChannelSummaryRow extends QueryResultRow {
  id: string;
  title: string;
  handle: string | null;
  channel_url: string;
  description: string | null;
  avatar_url: string | null;
  post_count: string | number;
}

function numericCount(value: string | number): number {
  const count = typeof value === "number" ? value : Number(value);
  if (!Number.isSafeInteger(count) || count < 0) {
    throw new Error(`Database returned an invalid count: ${String(value)}`);
  }
  return count;
}

function isoDate(value: Date | string | null): string | null {
  if (value === null) {
    return null;
  }

  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.valueOf())) {
    throw new Error("Database returned an invalid timestamp");
  }
  return date.toISOString();
}

function feedTags(value: unknown): FeedTag[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.map((item) => {
    if (
      typeof item !== "object" ||
      item === null ||
      typeof (item as { id?: unknown }).id !== "string" ||
      typeof (item as { name?: unknown }).name !== "string"
    ) {
      throw new Error("Database returned an invalid feed tag");
    }

    const category = (item as { category?: unknown }).category;
    if (category !== null && typeof category !== "string") {
      throw new Error("Database returned an invalid feed tag category");
    }

    return {
      id: (item as { id: string }).id,
      name: (item as { name: string }).name,
      category,
    };
  });
}

function feedPost(row: FeedRow): FeedPost {
  return {
    videoId: row.video_id,
    subtitleId: row.subtitle_id,
    youtubeVideoId: row.youtube_video_id,
    videoTitle: row.video_title,
    videoUrl: row.video_url,
    videoDescription: row.video_description,
    durationSeconds: row.duration_seconds,
    publishedAt: isoDate(row.published_at),
    transcript: row.transcript,
    languageCode: row.language_code,
    languageName: row.language_name,
    isAutoGenerated: row.is_auto_generated,
    channel: {
      id: row.channel_id,
      title: row.channel_title,
      handle: row.channel_handle,
      url: row.channel_url,
      description: row.channel_description,
      avatarUrl: row.channel_avatar_url,
    },
    tags: feedTags(row.tags),
  };
}

function tagSummary(row: TagSummaryRow): TagSummary {
  return {
    id: row.id,
    name: row.name,
    category: row.category,
    description: row.description,
    postCount: numericCount(row.post_count),
  };
}

function channelSummary(row: ChannelSummaryRow): ChannelSummary {
  return {
    id: row.id,
    title: row.title,
    handle: row.handle,
    url: row.channel_url,
    description: row.description,
    avatarUrl: row.avatar_url,
    postCount: numericCount(row.post_count),
  };
}

async function runtimePool(): Promise<Pool> {
  await connection();
  return getReadOnlyPool();
}

async function query<R extends QueryResultRow>(pool: Pool, spec: SqlQuery): Promise<R[]> {
  return (await pool.query<R>(spec.text, spec.values)).rows;
}

async function paginatedPosts(
  pool: Pool,
  specs: PagedSqlQueries,
  page: number,
): Promise<PaginatedResult<FeedPost>> {
  const [countRows, rows] = await Promise.all([
    query<CountRow>(pool, specs.count),
    query<FeedRow>(pool, specs.rows),
  ]);
  const totalItems = numericCount(countRows[0]?.total_count ?? 0);

  return {
    items: rows.map(feedPost),
    page,
    pageSize: PAGE_SIZE,
    totalItems,
    totalPages: Math.ceil(totalItems / PAGE_SIZE),
  };
}

async function getFeed(
  mode: "translated" | "original",
  input: FeedQueryInput,
): Promise<PaginatedResult<FeedPost>> {
  const parsed = parseFeedQuery(input);
  const pool = await runtimePool();
  return paginatedPosts(pool, buildFeedQueries({ ...parsed, mode }), parsed.page);
}

export async function getTranslatedFeed(
  input: FeedQueryInput = {},
): Promise<PaginatedResult<FeedPost>> {
  return getFeed("translated", input);
}

export async function getOriginalFeed(
  input: FeedQueryInput = {},
): Promise<PaginatedResult<FeedPost>> {
  return getFeed("original", input);
}

export async function getTags(): Promise<TagSummary[]> {
  const pool = await runtimePool();
  return (await query<TagSummaryRow>(pool, buildTagsQuery())).map(tagSummary);
}

export async function getTagDetail(
  tagId: string,
  input: FeedQueryInput = {},
): Promise<TagDetail | null> {
  if (!isUuid(tagId)) {
    return null;
  }

  const parsed = parseFeedQuery(input);
  const pool = await runtimePool();
  const tagQuery = buildTagSummaryQuery(tagId);
  const postQueries = buildTagFeedQueries(tagId, parsed);
  const [tagRows, posts] = await Promise.all([
    query<TagSummaryRow>(pool, tagQuery),
    paginatedPosts(pool, postQueries, parsed.page),
  ]);

  if (!tagRows[0]) {
    return null;
  }

  return {
    tag: tagSummary(tagRows[0]),
    posts,
  };
}

export async function getChannelDetail(
  channelId: string,
  input: ChannelFeedQueryInput = {},
): Promise<ChannelDetail | null> {
  if (!isUuid(channelId)) {
    return null;
  }

  const parsed = parseFeedQuery(input);
  const mode = input.mode === "original" ? "original" : "translated";
  const pool = await runtimePool();
  const channelQuery = buildChannelSummaryQuery(channelId);
  const postQueries = buildFeedQueries({ ...parsed, channelId, mode });
  const [channelRows, posts] = await Promise.all([
    query<ChannelSummaryRow>(pool, channelQuery),
    paginatedPosts(pool, postQueries, parsed.page),
  ]);

  if (!channelRows[0]) {
    return null;
  }

  return {
    channel: channelSummary(channelRows[0]),
    posts,
  };
}

export async function getSidebarData(): Promise<SidebarData> {
  const pool = await runtimePool();
  const [channelRows, tagRows] = await Promise.all([
    query<ChannelSummaryRow>(pool, buildSidebarChannelsQuery(SIDEBAR_CHANNEL_LIMIT)),
    query<TagSummaryRow>(pool, buildTopTagsQuery(SIDEBAR_TAG_LIMIT)),
  ]);

  return {
    channels: channelRows.map(channelSummary),
    topTags: tagRows.map(tagSummary),
  };
}
