export type SearchParamValue = string | string[] | number | null | undefined;

export type FeedMode = "translated" | "original";

export interface FeedQueryInput {
  q?: SearchParamValue;
  page?: SearchParamValue;
}

export interface ChannelFeedQueryInput extends FeedQueryInput {
  mode?: FeedMode;
}

export interface FeedTag {
  id: string;
  name: string;
  category: string | null;
}

export interface FeedChannel {
  id: string;
  title: string;
  handle: string | null;
  url: string;
  description: string | null;
  avatarUrl: string | null;
}

export interface FeedPost {
  videoId: string;
  subtitleId: string;
  youtubeVideoId: string;
  videoTitle: string;
  videoUrl: string;
  videoDescription: string | null;
  durationSeconds: number | null;
  publishedAt: string | null;
  transcript: string;
  languageCode: string;
  languageName: string | null;
  isAutoGenerated: boolean;
  channel: FeedChannel;
  tags: FeedTag[];
}

export interface PaginatedResult<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

export interface TagSummary {
  id: string;
  name: string;
  category: string | null;
  description: string | null;
  postCount: number;
}

export interface ChannelSummary {
  id: string;
  title: string;
  handle: string | null;
  url: string;
  description: string | null;
  avatarUrl: string | null;
  postCount: number;
}

export interface TagDetail {
  tag: TagSummary;
  posts: PaginatedResult<FeedPost>;
}

export interface ChannelDetail {
  channel: ChannelSummary;
  posts: PaginatedResult<FeedPost>;
}

export interface SidebarData {
  channels: ChannelSummary[];
  topTags: TagSummary[];
}
