import {
  ArrowLeft,
  Bot,
  Clock3,
  ExternalLink,
  FileText,
  Languages,
  Play,
} from "lucide-react";
import Link from "next/link";

import { Avatar } from "@/components/avatar";
import { formatDuration, formatPostDate } from "@/lib/post-format";
import { safeHttpUrl } from "@/lib/public-url";
import type { FeedMode, PostDetail as PostDetailData } from "@/lib/types";

export function PostDetail({
  detail,
  mode,
}: Readonly<{ detail: PostDetailData; mode: FeedMode }>) {
  const { post } = detail;
  const videoUrl = safeHttpUrl(post.videoUrl);
  const duration = formatDuration(post.durationSeconds);
  const transcript =
    mode === "translated" && detail.translatedTranscript
      ? detail.translatedTranscript
      : post.transcript;
  const language =
    mode === "translated" ? "简体中文" : post.languageName || post.languageCode;
  const backHref = mode === "translated" ? "/" : "/subtitles";
  const backLabel = mode === "translated" ? "返回首页" : "返回字幕";

  return (
    <article className="post-detail" aria-labelledby="post-detail-title">
      <header className="post-detail-header">
        <Link className="back-link" href={backHref}>
          <ArrowLeft size={15} aria-hidden="true" />
          {backLabel}
        </Link>

        <div className="post-detail-author-row">
          <Link
            className="post-detail-avatar"
            href={`/channels/${post.channel.id}`}
            aria-label={`查看${post.channel.title}`}
          >
            <Avatar src={post.channel.avatarUrl} name={post.channel.title} size={48} />
          </Link>
          <div className="post-detail-author-copy">
            <Link className="post-author" href={`/channels/${post.channel.id}`}>
              {post.channel.title}
            </Link>
            <div className="post-detail-author-meta">
              {post.channel.handle ? <span>{post.channel.handle}</span> : null}
              <time dateTime={post.publishedAt ?? undefined}>
                {formatPostDate(post.publishedAt)}
              </time>
            </div>
          </div>
          {videoUrl ? (
            <a
              className="post-detail-external"
              href={videoUrl}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="在 YouTube 打开"
              title="在 YouTube 打开"
            >
              <ExternalLink size={18} />
            </a>
          ) : null}
        </div>

        <h1 id="post-detail-title">{post.videoTitle}</h1>
        <div className="post-meta post-detail-meta">
          <span className="post-meta-item">
            <Languages size={14} aria-hidden="true" />
            {language}
          </span>
          <span>{post.isAutoGenerated ? "自动字幕" : "人工字幕"}</span>
          {duration ? (
            <span className="post-meta-item">
              <Clock3 size={13} aria-hidden="true" />
              {duration}
            </span>
          ) : null}
        </div>
        {videoUrl ? (
          <a
            className="post-detail-video-link"
            href={videoUrl}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Play size={15} fill="currentColor" aria-hidden="true" />
            在 YouTube 观看
          </a>
        ) : null}
      </header>

      <nav className="post-detail-tabs" aria-label="详情内容">
        <a href="#transcript-heading">
          <FileText size={15} aria-hidden="true" />
          字幕全文
        </a>
        <a href="#ai-analysis">
          <Bot size={15} aria-hidden="true" />
          AI 分析
        </a>
      </nav>

      <section className="post-transcript-section" aria-labelledby="transcript-heading">
        <h2 id="transcript-heading">字幕全文</h2>
        <p className="post-detail-transcript">{transcript}</p>
      </section>

      {post.tags.length ? (
        <footer className="post-detail-tags" aria-label="标签">
          {post.tags.map((tag) => (
            <Link className="tag-chip" href={`/tags/${tag.id}`} key={tag.id}>
              #{tag.name}
            </Link>
          ))}
        </footer>
      ) : null}
    </article>
  );
}
