import { Clock3, ExternalLink, Languages, Play } from "lucide-react";
import Link from "next/link";

import { Avatar } from "@/components/avatar";
import { TranscriptBody } from "@/components/transcript-body";
import { safeHttpUrl } from "@/lib/public-url";

export type TranscriptPostView = {
  videoId: string;
  subtitleId: string;
  youtubeVideoId: string;
  videoTitle: string;
  videoUrl: string;
  videoDescription: string | null;
  durationSeconds: number | null;
  publishedAt: string | null;
  transcript: string;
  languageCode: string;
  languageName: string | null;
  isAutoGenerated: boolean;
  channel: {
    id: string;
    title: string;
    handle: string | null;
    url: string;
    description: string | null;
    avatarUrl: string | null;
  };
  tags: Array<{
    id: string;
    name: string;
    category: string | null;
  }>;
};

function formatPublishedAt(value: string | null) {
  if (!value) return "日期未知";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "日期未知";
  return new Intl.DateTimeFormat("zh-CN", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "Asia/Shanghai",
  }).format(date);
}

function formatDuration(seconds: number | null) {
  if (seconds === null) return null;
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remainingSeconds = seconds % 60;
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`
    : `${minutes}:${String(remainingSeconds).padStart(2, "0")}`;
}

export function TranscriptPost({
  post,
  mode,
}: Readonly<{ post: TranscriptPostView; mode: "translated" | "original" }>) {
  const date = formatPublishedAt(post.publishedAt);
  const duration = formatDuration(post.durationSeconds);
  const videoUrl = safeHttpUrl(post.videoUrl);
  const language =
    mode === "translated" ? "简体中文" : post.languageName || post.languageCode;

  return (
    <article className="transcript-post">
      <Link href={`/channels/${post.channel.id}`} aria-label={`查看${post.channel.title}`}>
        <Avatar src={post.channel.avatarUrl} name={post.channel.title} />
      </Link>

      <div className="post-content">
        <div className="post-byline">
          <Link className="post-author" href={`/channels/${post.channel.id}`}>
            {post.channel.title}
          </Link>
          {post.channel.handle ? <span className="post-handle">{post.channel.handle}</span> : null}
          <span className="byline-dot" aria-hidden="true">
            ·
          </span>
          <time className="post-date" dateTime={post.publishedAt ?? undefined}>
            {date}
          </time>
          {videoUrl ? (
            <a
              className="post-menu-link"
              href={videoUrl}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="在 YouTube 打开"
              title="在 YouTube 打开"
            >
              <ExternalLink size={17} />
            </a>
          ) : null}
        </div>

        <h2 className="post-title">
          {videoUrl ? (
            <a href={videoUrl} target="_blank" rel="noopener noreferrer">
              {post.videoTitle}
            </a>
          ) : (
            post.videoTitle
          )}
        </h2>

        <div className="post-meta">
          <span className="post-meta-item">
            <Languages size={14} aria-hidden="true" />
            {language}
          </span>
          {post.isAutoGenerated ? <span>自动字幕</span> : <span>人工字幕</span>}
          {duration ? (
            <span className="post-meta-item">
              <Clock3 size={13} aria-hidden="true" />
              {duration}
            </span>
          ) : null}
        </div>

        <TranscriptBody text={post.transcript} />

        {videoUrl ? (
          <a
            className="video-attachment"
            href={videoUrl}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={`播放 ${post.videoTitle}`}
          >
            <span className="video-thumbnail">
              {/* YouTube IDs produce a stable first-party thumbnail URL. */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`https://i.ytimg.com/vi/${encodeURIComponent(post.youtubeVideoId)}/mqdefault.jpg`}
                alt=""
                width="320"
                height="180"
                loading="lazy"
              />
              <span className="play-mark" aria-hidden="true">
                <Play size={15} fill="currentColor" />
              </span>
            </span>
            <span className="video-attachment-copy">
              <span className="attachment-source">youtube.com</span>
              <span className="attachment-title">{post.videoTitle}</span>
            </span>
          </a>
        ) : null}

        {post.tags.length ? (
          <footer className="post-footer" aria-label="标签">
            {post.tags.map((tag) => (
              <Link className="tag-chip" href={`/tags/${tag.id}`} key={tag.id}>
                #{tag.name}
              </Link>
            ))}
          </footer>
        ) : null}
      </div>
    </article>
  );
}
